# Generated by Django 5.2.8 on 2025-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="car_size",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small"), ("big", "Big")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="address_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
