# Generated by Django 5.2.8 on 2025-12-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_booking_car_size_booking_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="car_size",
            field=models.CharField(
                blank=True,
                choices=[("small", "سيارة صغيرة"), ("large", "سيارة كبيرة")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
