# Generated by Django 5.2.8 on 2025-12-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_booking_unique_together_alter_booking_car_size_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("date", "time_slot")},
        ),
        migrations.AlterField(
            model_name="booking",
            name="car_size",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small Car"), ("big", "Big Car")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("on_the_way", "On the way"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="customer_phone",
        ),
    ]
