# Generated by Django 5.2.8 on 2025-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_booking_unique_together_alter_booking_car_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay / Android Pay"),
                    ("mada", "Mada"),
                    ("cash", "Cash"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="car_size",
            field=models.CharField(
                blank=True,
                choices=[("small", "سيارة صغيرة"), ("big", "سيارة كبيرة")],
                max_length=10,
                null=True,
            ),
        ),
    ]
