# Generated by Django 5.2.8 on 2026-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_seed_vehicle_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(default='sedan', max_length=20),
        ),
    ]
