# Generated by Django 5.2.8 on 2026-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('card', 'شبكة'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني')], default='cash', max_length=20),
        ),
    ]
