# Generated by Django 5.2.8 on 2026-09-12 21:49

from django.db import migrations, models
from datetime import time


def seed_booking_time_slots(apps, schema_editor):
    BookingTimeSlot = apps.get_model('api', 'BookingTimeSlot')
    slots = [
        ('9 صباحاً', time(9, 0), 0),
        ('10 صباحاً', time(10, 0), 0),
        ('11 صباحاً', time(11, 0), 0),
        ('4 مساءً', time(16, 0), 0),
        ('5 مساءً', time(17, 0), 0),
        ('6 مساءً', time(18, 0), 0),
        ('7 مساءً', time(19, 0), 0),
        ('8 مساءً', time(20, 0), 0),
        ('9 مساءً', time(21, 0), 0),
        ('10 مساءً', time(22, 0), 0),
        ('11 مساءً', time(23, 0), 0),
        ('12 مساءً', time(0, 0), 1),
    ]
    for label, start_time, day_offset in slots:
        BookingTimeSlot.objects.get_or_create(
            label=label,
            defaults={
                'start_time': start_time,
                'day_offset': day_offset,
                'is_active': True,
            },
        )


def remove_booking_time_slots(apps, schema_editor):
    BookingTimeSlot = apps.get_model('api', 'BookingTimeSlot')
    BookingTimeSlot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_expense_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField()),
                ('day_offset', models.PositiveSmallIntegerField(choices=[(0, 'نفس اليوم'), (1, 'نهاية اليوم بعد منتصف الليل')], default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_offset', 'start_time', 'id'],
                'constraints': [models.UniqueConstraint(fields=('start_time', 'day_offset'), name='unique_booking_slot_clock_time')],
            },
        ),
        migrations.RunPython(
            seed_booking_time_slots,
            remove_booking_time_slots,
        ),
    ]
